# Generated by Django 5.1.2 on 2025-05-22 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome da Categoria')),
                ('slug', models.SlugField(help_text='Identificador único para URL (ex: esfihas-abertas)', max_length=100, unique=True)),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('ordem', models.PositiveIntegerField(default=0, help_text='Define a ordem de exibição das categorias')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco_unitario_historico', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço Unitário (na compra)')),
                ('quantidade', models.PositiveIntegerField(default=1, verbose_name='Quantidade')),
                ('nome_produto_historico', models.CharField(max_length=255, verbose_name='Nome do Produto (na compra)')),
            ],
            options={
                'verbose_name': 'Item do Pedido',
                'verbose_name_plural': 'Itens do Pedido',
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=150, verbose_name='Nome Completo')),
                ('telefone', models.CharField(max_length=20, verbose_name='Telefone (com DDD)')),
                ('endereco_rua', models.CharField(max_length=255, verbose_name='Rua/Avenida')),
                ('endereco_numero', models.CharField(max_length=20, verbose_name='Número')),
                ('endereco_complemento', models.CharField(blank=True, max_length=100, null=True, verbose_name='Complemento (Apto, Bloco, etc.)')),
                ('endereco_bairro', models.CharField(max_length=100, verbose_name='Bairro')),
                ('endereco_cidade', models.CharField(default='Peruíbe', max_length=100, verbose_name='Cidade')),
                ('endereco_cep', models.CharField(blank=True, max_length=9, null=True, verbose_name='CEP (Opcional)')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações do Pedido')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('valor_total_pedido', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Total do Pedido')),
                ('forma_pagamento', models.CharField(choices=[('dinheiro', 'Dinheiro na Entrega'), ('cartao_debito', 'Cartão de Débito na Entrega'), ('cartao_credito', 'Cartão de Crédito na Entrega'), ('pix', 'PIX na Entrega')], default='dinheiro', max_length=20, verbose_name='Forma de Pagamento')),
                ('troco_para', models.DecimalField(blank=True, decimal_places=2, help_text='Preencher somente se pagamento for em dinheiro e precisar de troco.', max_digits=10, null=True, verbose_name='Troco para (R$)')),
                ('status', models.CharField(choices=[('recebido', 'Recebido'), ('em_preparo', 'Em Preparo'), ('saiu_para_entrega', 'Saiu para Entrega'), ('entregue', 'Entregue'), ('cancelado', 'Cancelado')], default='recebido', max_length=20, verbose_name='Status do Pedido')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do Produto')),
                ('descricao', models.TextField(verbose_name='Descrição Detalhada')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço (R$)')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='produtos_imagens/', verbose_name='Imagem do Produto')),
                ('disponivel', models.BooleanField(default=True, verbose_name='Disponível?')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ['nome'],
            },
        ),
    ]
