# Generated by Django 5.1.2 on 2025-05-23 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardapio', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itempedido',
            name='preco_unitario_historico',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Preço Unitário (na compra)'),
        ),
    ]
