# Generated by Django 5.1.2 on 2024-11-12 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('email', models.CharField(max_length=50, verbose_name='E-mail')),
                ('whatsapp', models.CharField(max_length=15, verbose_name='WhatsApp')),
            ],
        ),
    ]
