# Generated by Django 5.1.2 on 2025-05-22 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='Nota de 1 a 5 estrelas')),
                ('comentario', models.TextField(blank=True, help_text='Comentário opcional sobre o pedido', null=True)),
                ('data_avaliacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-data_avaliacao'],
            },
        ),
    ]
